---
title: "Data Visualization | Fall 2025 @AU"
subtitle: "Multivariate Analysis of GSS Data"
author: "Anne Skamris Holm and Nour Alsaid"
date: "`r Sys.Date()`"
header-includes:
- \usepackage{fancyhdr}
output:
  html_document:
    toc: yes
    number_sections: yes
    toc_float: yes
    theme: united
    highlight: espresso
  pdf_document:
    latex_engine: xelatex
    toc: true #Created table from headings
    number_sections: yes
  #always_allow_html: true
geometry: margin=1in
---

\pagestyle{fancy}
\fancyhead[HL]{Data Visualization} 
\fancyhead[HR]{Anne Skamris Holm and Nour Alsaid}

\newpage
```{r setup, include=FALSE}
# include = F results in coding chunks in doc not being printed
knitr::opts_chunk$set(echo = FALSE, include = TRUE, message = FALSE, warning = FALSE)

# Resetting the environment
rm(list=ls()) # clears global workspace

# Setting working directory
knitr::opts_knit$set(root.dir = '.')
getwd()

# Loading packages
pacman::p_load(tidyverse, pastecs, gridExtra, ggplot2, tinytex, shiny, bslib, plotly, webshot2, sf, jsonlite)

```

# Part 1

## Importing GSS data

```{r converting to CSV}
library(foreign)
  read.dct <- function(dct, labels.included = "yes") {
      temp <- readLines(dct)
      temp <- temp[grepl("_column", temp)]
      switch(labels.included,
             yes = {
                 pattern <- "_column\\(([0-9]+)\\)\\s+([a-z0-9]+)\\s+(.*)\\s+%([0-9]+)[a-z]\\s+(.*)"
                 classes <- c("numeric", "character", "character", "numeric", "character")
                 N <- 5
                 NAMES <- c("StartPos", "Str", "ColName", "ColWidth", "ColLabel")
             },
             no = {
                 pattern <- "_column\\(([0-9]+)\\)\\s+([a-z0-9]+)\\s+(.*)\\s+%([0-9]+).*"
                 classes <- c("numeric", "character", "character", "numeric")
                 N <- 4
                 NAMES <- c("StartPos", "Str", "ColName", "ColWidth")
             })
      temp_metadata <- setNames(lapply(1:N, function(x) {
          out <- gsub(pattern, paste("\\", x, sep = ""), temp)
          out <- gsub("^\\s+|\\s+$", "", out)
          out <- gsub('\"', "", out, fixed = TRUE)
          class(out) <- classes[x] ; out }), NAMES)
      temp_metadata[["ColName"]] <- make.names(gsub("\\s", "", temp_metadata[["ColName"]]))
      temp_metadata
  }

  read.dat <- function(dat, metadata_var, labels.included = "yes") {
      read.table(dat, col.names = metadata_var[["ColName"]])
  }


GSS_metadata <- read.dct("data/exploring_variables/GSS.dct")
GSS_ascii <- read.dat("data/exploring_variables/GSS.dat", GSS_metadata)
attr(GSS_ascii, "col.label") <- GSS_metadata[["ColLabel"]]
GSS <- GSS_ascii
  
# Save as csv
GSS %>% 
  write_csv(file = "data/exploring_variables/GSS_data.csv")

GSS_ascii %>% 
  write_csv(file = "data/exploring_variables/GSS_data_ascii.csv")

```




## Preprocessing GSS data
```{r}
df_fresh <-read_csv('data/exploring_variables/GSS_data.csv')

#Insert row number ('ID') variable to the data frame
df_fresh <- dplyr::mutate(df_fresh, ID = row_number()) #generates student IDs by row number.

# Rename columns so they are all uppercase
df <- df_fresh %>%
  select(
    ID,
    GSS_ID=ID_,
    year=YEAR,
    sex_num=SEX,
    age=AGE,
    region=REGION,
    happiness=HAPPY,
    educ=EDUC,
    race=RACE,
    work=WRKSTAT,
    marital=MARITAL
)

df <- df %>%
  mutate(
    across(where(is.character), as.factor),
    ID = as.factor(ID),
    
    year = as.numeric(year),
    
    age = as.numeric(age),
    age= case_when(age < 0 ~ NA_real_, age>0~age),
    
    sex_num = as.factor(sex_num),
    sex = case_when(sex_num=="1"~"M", sex_num=="2"~"F", TRUE ~ NA_character_),
    
    region = as.factor(region),
    region = recode(region, "1" = "New England", "2" = "Middle Atlantic",  "3" = "East North Central",  "4" = "West North Central", "5" = "South Atlantic",  "6" = "East South Central",  "7" = "West South Central",  "8" = "Mountain",  "9" = "Pacific"),
    
    happiness = as.character(happiness),
    happiness = recode(happiness, "1" = "Very happy", "2" = "Pretty happy", "3" = "Not too happy", "-98" = NA_character_, "-100" = NA_character_, "-99" = NA_character_, "-97" = NA_character_),
    
    race = as.character(race),
    race = recode(race, "-100" = NA_character_),
    race = recode(race, "1" = "White", "2" = "Black", "3" = "Other"),
    
    
    educ = as.character(educ),
    educ = recode(educ, "-98" = NA_character_, "-99" = NA_character_),
    educ = recode(educ, "0" = "No formal schooling", "1" = "1st grade", "2" = "2nd grade", "3" = "3rd grade", "4" = "4th grade", "5" = "5th grade", "6" = "6th grade", "7" = "7th grade", "8" = "8th grade", "9" = "9th grade", "10"= "10th grade", "11" = "11th grade", "12" = "12th grade", "13"= "1 year of college", "14" = "2 years of college",  "15"="3 years of collage", "16" = "4 years of college", "17" = "5 years of college", "18" = "6 years of college", "19" = "7 years of college", "20" = "8 or more years of college"),
    
    
    work = as.character(work),
    work = recode(work, "-97" = NA_character_, "-98" = NA_character_, "-99" = NA_character_),
    work = recode(work, "1" = "Working full time", "2" = "Working part time", "3" = "With a job, but home", "4" = "Unemployed", "5" = "Retired", "6" = "In school", "7" = "Keeping house", "8" = "Other"),
    
    marital = as.character(marital),
    marital = recode(marital, "-97" = NA_character_, "-98" = NA_character_, "-99" = NA_character_),
    marital = recode(marital, "1" = "Married", "2" = "Widowed", "3" = "Divorced", "4" = "Sepreated", "5" = "Never married")
  )

head(df)
```



### cleaning the data, eg. removing NA's
```{r}
# Creating df_clean with chosen variables
df_clean <- df %>%
  select(
    year,
    sex,
    age,
    region,
    happiness,
    educ,
    race,
    work,
    marital
)

# Counting NA's in the full data
data.frame(
  na_count = colSums(is.na(df_clean)),
  na_percent = round(colSums(is.na(df_clean)) / nrow(df_clean) * 100, 1)
)

# Create simple missingness map
library(naniar)
vis_miss(df_clean)

# Creating df_NA consisting of the data removed
df_NA <- df_clean %>%
  filter(is.na(age) | is.na(sex) | is.na(region) | is.na(year) | is.na(happiness))


# Removing NA's
df_clean <- na.omit(df_clean)
#df_clean <- df_clean %>%
#  filter(!is.na(age), !is.na(sex), !is.na(region))


# Adding age ranges after cleaning

# Source - https://stackoverflow.com/questions/51095156/how-to-group-ages-in-specific-range-using-r
# Posted by Rui Barradas
# Retrieved 2025-11-12, License - CC BY-SA 4.0
age_ranges <- cut(df_clean$age, c(18, seq(19, 88, by = 2), 89), 
                  labels = paste(seq(18, 88, by = 2), "to", seq(19, 89, by = 2)), 
                  include.lowest = TRUE)

df_clean$age_ranges <- age_ranges


list_year <- unique(df_clean$year)

year_ranges <-cut(df_clean$year, 
      breaks = seq(min(df_clean$year), max(df_clean$year), by = 2),
      labels = paste(seq(1972, 2022, by = 2), "to", seq(1973, 2023, by = 2)),
      include.lowest = TRUE)

df_clean$year_ranges <- year_ranges



# Counting NA's in df_clean (No NA's)
data.frame(
  #column = names(df_clean),
  na_count = colSums(is.na(df_clean)),
  na_percent = round(colSums(is.na(df_clean)) / nrow(df_clean) * 100, 1)
)

write.csv(df_clean, "data_vis_shiny_app/df_clean.csv", row.names = FALSE)
```









## Exploring GSS data

### Distribution of Data
```{r}
#YEAR
# Year including NA's
year_w_na <- ggplot(df, aes(x = year)) + 
  theme_minimal() + 
  labs(x = "Year", title = "Years with NA's") + 
  geom_bar(binwidth = 1)+
  coord_cartesian(ylim = c(0, 4000))  # sets y-axis range

# Year NA's removed
year_clean <- ggplot(df_clean, aes(x = year)) + 
  theme_minimal() + 
  labs(x = "Year", title = "Years with NA's removed") + 
  geom_bar(binwidth = 1)+
  coord_cartesian(ylim = c(0, 4000))  # sets y-axis range

# Year NA's 
year_na <- ggplot(df_NA, aes(x = year)) + 
  theme_minimal() + 
  labs(x = "Year", title = "Year removed responses") + 
  geom_bar(binwidth = 1)+
  coord_cartesian(ylim = c(0, 4000))  # sets y-axis range

#AGE
# age including NA's
age_w_na <- ggplot(df, aes(x = age)) + 
  theme_minimal() + 
  labs(x = "age", title = "ages with NA's") + 
  geom_bar(binwidth = 1)+
  coord_cartesian(ylim = c(0, 4000))  # sets y-axis range

# age NA's removed
age_clean <- ggplot(df_clean, aes(x = age)) + 
  theme_minimal() + 
  labs(x = "age", title = "ages with NA's removed") + 
  geom_bar(binwidth = 1)+
  coord_cartesian(ylim = c(0, 4000))  # sets y-axis range

# age NA's 
age_na <- ggplot(df_NA, aes(x = age)) + 
  theme_minimal() + 
  labs(x = "age", title = "age removed responses") + 
  geom_bar(binwidth = 1)+
  coord_cartesian(ylim = c(0, 4000))  # sets y-axis range

#REGION
# region including NA's
region_w_na <- ggplot(df, aes(x = region, fill=sex)) + 
  theme_minimal() + 
  labs(x = "region", title = "region with NA's") + 
  geom_bar(position = position_dodge(width = 0.9))+
  coord_cartesian(ylim = c(0, 15000))  # sets y-axis range

# region NA's removed
region_clean <- ggplot(df_clean, aes(x = region, fill=sex)) + 
  theme_minimal() + 
  labs(x = "region", title = "region groups with NA's removed") + 
  geom_bar(position = position_dodge(width = 0.9))+
  coord_cartesian(ylim = c(0, 15000))  # sets y-axis range
 
# region NA's 
region_na <- ggplot(df_NA, aes(x = region, fill=sex)) + 
  theme_minimal() + 
  labs(x = "region", title = "region removed respones") + 
  geom_bar(position = position_dodge(width = 0.9))+
  coord_cartesian(ylim = c(0, 15000))  # sets y-axis range

#SEX
# sex including NA's
sex_w_na <- ggplot(df, aes(x = sex, fill=sex)) + 
  theme_minimal() + 
  labs(x = "sex", title = "sex with NA's") + 
  geom_bar(position = position_dodge(width = 0.9))+
  coord_cartesian(ylim = c(0, 40000))  # sets y-axis range

# sex NA's removed
sex_clean <- ggplot(df_clean, aes(x = sex, fill=sex)) + 
  theme_minimal() + 
  labs(x = "sex", title = "sex groups with NA's removed") + 
  geom_bar(position = position_dodge(width = 0.9))+
  coord_cartesian(ylim = c(0, 40000))  # sets y-axis range
 
# sex NA's 
sex_na <- ggplot(df_NA, aes(x = sex, fill=sex)) + 
  theme_minimal() + 
  labs(x = "sex", title = "sex removed respones") + 
  geom_bar(position = position_dodge(width = 0.9))+
  coord_cartesian(ylim = c(0, 40000))  # sets y-axis range


#HAPPINESS
# Happiness including NA's
happy_w_na <- ggplot(df, aes(x = happiness, fill=sex)) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 1, hjust = 1, size = rel(.80))) + 
  labs(x = "Happiness", title = "Happiness with NA's") + 
  geom_bar(position = position_dodge(width = 0.9))+
  coord_cartesian(ylim = c(0, 20000))  # sets y-axis range

# Happiness NA's removed
happy_clean <- ggplot(df_clean, aes(x = happiness, fill=sex)) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 1, hjust = 1, size = rel(.80))) + 
  labs(x = "Happiness", title = "Happiness groups with NA's removed") + 
  geom_bar(position = position_dodge(width = 0.9))+
  coord_cartesian(ylim = c(0, 20000))  # sets y-axis range

# Happiness NA's 
happy_na <- ggplot(df_NA, aes(x = happiness, fill=sex)) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 1, hjust = 1, size = rel(.80))) + 
  labs(x = "Happiness", title = "Happiness removed respones") + 
  geom_bar(position = position_dodge(width = 0.9))+
  coord_cartesian(ylim = c(0, 20000))  # sets y-axis range

#RACE
# race including NA's
race_w_na <- ggplot(df, aes(x = race, fill=sex)) + 
  theme_minimal() + 
  labs(x = "race", title = "race with NA's") + 
  geom_bar(position = position_dodge(width = 0.9))+
  coord_cartesian(ylim = c(0, 35000))  # sets y-axis range

# race NA's removed
race_clean <- ggplot(df_clean, aes(x = race, fill=sex)) + 
  theme_minimal() + 
  labs(x = "race", title = "race groups with NA's removed") + 
  geom_bar(position = position_dodge(width = 0.9))+
  coord_cartesian(ylim = c(0, 35000))  # sets y-axis range
 
# race NA's 
race_na <- ggplot(df_NA, aes(x = race, fill=sex)) + 
  theme_minimal() + 
  labs(x = "race", title = "race removed respones") + 
  geom_bar(position = position_dodge(width = 0.9))+
  coord_cartesian(ylim = c(0, 35000))  # sets y-axis range

#MARITAL
# marital including NA's
marital_w_na <- ggplot(df, aes(x = marital, fill=sex)) + 
  theme_minimal() + 
  labs(x = "marital", title = "marital with NA's") + 
  geom_bar(position = position_dodge(width = 0.9))+
  coord_cartesian(ylim = c(0, 21000))  # sets y-axis range

# marital NA's removed
marital_clean <- ggplot(df_clean, aes(x = marital, fill=sex)) + 
  theme_minimal() + 
  labs(x = "marital", title = "marital groups with NA's removed") + 
  geom_bar(position = position_dodge(width = 0.9))+
  coord_cartesian(ylim = c(0, 21000))  # sets y-axis range
 
# marital NA's 
marital_na <- ggplot(df_NA, aes(x = marital, fill=sex)) + 
  theme_minimal() + 
  labs(x = "marital", title = "marital removed respones") + 
  geom_bar(position = position_dodge(width = 0.9))+
  coord_cartesian(ylim = c(0, 21000))  # sets y-axis range

#EDUCATION
# educ including NA's
educ_w_na <- ggplot(df, aes(x = educ, fill=sex)) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 1, hjust = 1, size = rel(.80))) + 
  labs(x = "educ", title = "educ with NA's") + 
  geom_bar(position = position_dodge(width = 0.9))+
  coord_cartesian(ylim = c(0, 15000))  # sets y-axis range

# educ NA's removed
educ_clean <- ggplot(df_clean, aes(x = educ, fill=sex)) + 
  labs(x = "educ", title = "educ groups with NA's removed") + 
  geom_bar(position = position_dodge(width = 0.9))+
  theme(axis.text.x = element_text(angle = 90, vjust = 1, hjust = 1, size = rel(.80)))+
  coord_cartesian(ylim = c(0, 15000))  # sets y-axis range
 
# educ NA's 
educ_na <- ggplot(df_NA, aes(x = educ, fill=sex)) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 1, hjust = 1, size = rel(.80))) + 
  labs(x = "educ", title = "educ removed respones") + 
  geom_bar(position = position_dodge(width = 0.9))+
  coord_cartesian(ylim = c(0, 15000))  # sets y-axis range

#WORK
# work including NA's
work_w_na <- ggplot(df, aes(x = work, fill=sex)) + 
  theme_minimal() + 
  labs(x = "work", title = "work with NA's") + 
  geom_bar(position = position_dodge(width = 0.9))+
  coord_cartesian(ylim = c(0, 20000))  # sets y-axis range

# work NA's removed
work_clean <- ggplot(df_clean, aes(x = work, fill=sex)) + 
  theme_minimal() + 
  labs(x = "work", title = "work groups with NA's removed") + 
  geom_bar(position = position_dodge(width = 0.9))+
  coord_cartesian(ylim = c(0, 20000))  # sets y-axis range
 
# work NA's 
work_na <- ggplot(df_NA, aes(x = work, fill=sex)) + 
  theme_minimal()+ 
  labs(x = "work", title = "work removed respones") + 
  geom_bar(position = position_dodge(width = 0.9))+
  coord_cartesian(ylim = c(0, 20000))  # sets y-axis range

grid.arrange(year_w_na, year_clean, year_na, ncol=2)
grid.arrange(age_w_na, age_clean, age_na, ncol=2)
grid.arrange(region_w_na, region_clean, region_na, ncol=2)
grid.arrange(sex_w_na, sex_clean, sex_na, ncol=2)
grid.arrange(happy_w_na, happy_clean, happy_na, ncol=2)
grid.arrange(race_w_na, race_clean, race_na, ncol=2)
grid.arrange(marital_w_na, marital_clean, marital_na, ncol=2)
grid.arrange(educ_w_na, educ_clean, educ_na, ncol=2)
grid.arrange(work_w_na, work_clean, work_na, ncol=2)
```

# Part 2 -building the app

## Functions for the map

### Creating map
```{r}
# Define mapping of regions to state abbreviations
us_regions <- list(
  "New England" = c("CT", "ME", "MA", "NH", "RI", "VT"),
  "Middle Atlantic" = c("NJ", "NY", "PA"),
  "East North Central" = c("IL", "IN", "MI", "OH", "WI"),
  "West North Central" = c("IA", "KS", "MN", "MO", "NE", "ND", "SD"),
  "South Atlantic" = c("DE", "DC", "FL", "GA", "MD", "NC", "SC", "VA", "WV"),
  "East South Central" = c("AL", "KY", "MS", "TN"),
  "West South Central" = c("AR", "LA", "OK", "TX"),
  "Mountain" = c("AZ", "CO", "ID", "MT", "NV", "NM", "UT", "WY"),
  "Pacific" = c("AK", "CA", "HI", "OR", "WA")
)

# Convert the list to a tidy dataframe
region_to_state_df <- tibble(
  region = rep(names(us_regions), lengths(us_regions)),
  state = unlist(us_regions)
)

library(sf)
library(leaflet)

# Loading map
my_map <- read_sf("data_vis_shiny_app/us_states/cb_2024_us_state_500k.shp")

# Simplify polygons to speed up rendering (the higher the faster)
my_map <- my_map %>%
  st_simplify(my_map, dTolerance = 20000) %>%# adjust tolerance
  sf::st_transform(crs = 4326)

#Adding column with region names
my_map <- my_map %>%
  rename(state=STUSPS)%>%
  filter(!state %in% c("AS", "GU", "MP", "PR", "VI"))%>%
  left_join(region_to_state_df %>% select(state, region), by = "state")


#Converting states to regions 
map_data <- my_map %>%
  group_by(region) %>%
  summarise(geometry = st_union(geometry))  # merge polygons

# Write shapefile
st_write(map_data, "data_vis_shiny_app/data_map.shp", delete_dsn = TRUE, quiet = TRUE)
```

### Creating data
```{r}
# Assign the data 
library(dplyr)
library(readr)

# Define your decades and regions
decades <- list(
  "1970's" = 1970:1979,
  "1980's" = 1980:1989,
  "1990's" = 1990:1999,
  "2000's" = 2000:2009,
  "2010's" = 2010:2019,
  "2020's" = 2020:2029
)

regions <- c(
  "New England", "Middle Atlantic", "East North Central", "West North Central",
  "South Atlantic", "East South Central", "West South Central", "Mountain", "Pacific"
)

# Create a complete grid of all combinations (even if missing in data)
df_happy <- expand_grid(
  sex = unique(df_clean$sex),
  happiness = unique(df_clean$happiness),
  region = regions,
  year = names(decades)
)

write.csv(df_happy, "data_vis_shiny_app/data_happy.csv", row.names = FALSE)

# Create a complete grid of all combinations of educ
df_educ <- expand_grid(
  sex = unique(df_clean$sex),
  educ = unique(df_clean$educ),
  region = regions,
  year = names(decades)
)

write.csv(df_educ, "data_vis_shiny_app/data_educ.csv", row.names = FALSE)
unique(df_educ$educ)

# Create a complete grid of all combinations of educ
df_marital <- expand_grid(
  sex = unique(df_clean$sex),
  marital = unique(df_clean$marital),
  region = regions,
  year = names(decades)
)
unique(df_marital$marital)

write.csv(df_marital, "data_vis_shiny_app/data_marital.csv", row.names = FALSE)
```


# Checking data
```{r}
df_var <- "marital" #and educ
df_data <- df_marital

df_sym <- rlang::sym(df_var)  # convert string → symbol

df_simple <- purrr::map_dfr(
  names(decades),
  \(decade) {
    purrr::map_dfr(
      regions,
      \(reg) {
        df_clean %>%
          filter(year %in% decades[[decade]], region == reg) %>%
          group_by(sex, !!df_sym) %>%
          summarise(count = n(), .groups = "drop") %>%
          group_by(sex) %>%
          mutate(
            perc = count / sum(count) * 100,
            region = reg,
            year = decade
          ) 
      }
    )
  }
)

# Calculating percentage differences
df_all <- df_data %>%
  left_join(df_simple, by = c("sex", df_var, "region", "year")) %>%
  mutate(
    count = replace_na(count, 0),
    perc = replace_na(perc, 0)
  ) %>%
  arrange(year, region, sex, !!df_sym)

df_new <- df_all%>%
  filter(!count==0)

unique(df_clean$region)
```
```{r}
#Function to create data
function_filter <- function (df_var, df_data) {

df_sym <- rlang::sym(df_var)  # convert string → symbol

df_simple <- purrr::map_dfr(
  names(decades),
  \(decade) {
    purrr::map_dfr(
      regions,
      \(reg) {
        df_clean %>%
          filter(year %in% decades[[decade]], region == reg) %>%
          group_by(sex, !!df_sym) %>%
          summarise(count = n(), .groups = "drop") %>%
          group_by(sex) %>%
          mutate(
            perc = count / sum(count) * 100,
            region = reg,
            year = decade
          ) 
      }
    )
  }
)
# Calculating percentage differences
df_all <- df_data %>%
  left_join(df_simple, by = c("sex", df_var, "region", "year")) %>%
  mutate(
    count = replace_na(count, 0),
    perc = replace_na(perc, 0)
  ) %>%
  arrange(year, region, sex, !!df_sym)


df_dif <- df_all %>%
  select(-"count")%>%
  pivot_wider(
    names_from = sex,
    values_from = perc
  ) %>%
  mutate(
    percent = `F` - `M`  # difference between male and female percentages
  ) 

}

```

```{r}

df_happy_final <- function_filter(
  df_var = "happiness",
  df_data = df_happy
)

df_marital_final <- function_filter(
  df_var = "marital",
  df_data = df_marital
)

df_marital_educ <- function_filter(
  df_var = "educ",
  df_data = df_educ
)

head(df_marital_final)
```


# Part 3
## Run the app
```{r}
library(shiny)
# runApp("data_vis_shiny_app") #Shows only the app and no code

#runApp("data_vis_shiny_app", display.mode = "showcase") #Shows the code as well and highlights chinks with interaction
```